#!/bin/sh

set -e
CONFIG=$1
shift
PACKAGES=$@
PP=`ocamlfind query -r ${PACKAGES} -predicates preprocessor,syntax,camlp4o -format "    \"-I\" \"%d\" \"%a\""`

echo "begin config \"${CONFIG}\"
  pp  = [ \"camlp4\"
${PP}  ]
end
"