#!/bin/sh

set -e
PACKAGE=$1
DIRNAME=`ocamlfind query ${PACKAGE}`
REQUIRES=`ocamlfind query ${PACKAGE} -r -format '    "%p"' | grep -v "${PACKAGE}"`

echo "begin library \"${PACKAGE}\"
  generated = true
  directory = \"${DIRNAME}\"
  requires  = [
${REQUIRES}  ]
end
"